name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: YasinChan/vuepress-blog
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://www.xxx.com
